/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SupavisioJ.FrameConfigXYEList;

import SupavisioJ.MainFrame.MainFrame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.AbstractButton;
import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

public class FrameConfigXYEList extends JFrame implements FocusListener {

    private MainFrame supavisioJFrame;
    /**
     * Creates new form FrameConfigXYEList
     */
    public FrameConfigXYEList(MainFrame supavisioJFrame) {
        initComponents();
        this.supavisioJFrame = supavisioJFrame;
        jTextFieldNbField.addFocusListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNbField = new JTextField();
        jLabelNbFields = new JLabel();
        jCheckBoxSetDefaultSave = new JCheckBox();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldNbField.setText(tr("number"));

        jLabelNbFields.setText(tr("fields to affich"));

        jCheckBoxSetDefaultSave.setText(tr("Use predefined values"));
        jCheckBoxSetDefaultSave.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBoxSetDefaultSaveActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxSetDefaultSave, GroupLayout.PREFERRED_SIZE, 208, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNbField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNbFields)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNbField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNbFields))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxSetDefaultSave)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxSetDefaultSaveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSetDefaultSaveActionPerformed
        AbstractButton AB = (AbstractButton) evt.getSource();
        supavisioJFrame.setFillWithPredefValXYEList(AB.getModel().isSelected());
    }//GEN-LAST:event_jCheckBoxSetDefaultSaveActionPerformed
    public static String tr(String dataToTranslate){
        return MainFrame.tr(dataToTranslate);
    }
    
    @Override
    public void focusGained(FocusEvent e) {}

    @Override
    public void focusLost(FocusEvent evt) {
        String input = jTextFieldNbField.getText();
        try {
            int nbFields = Integer.valueOf(input);
            supavisioJFrame.setNbFieldXYEList(nbFields);
        }
        catch (NumberFormatException e){}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JCheckBox jCheckBoxSetDefaultSave;
    private JLabel jLabelNbFields;
    private JTextField jTextFieldNbField;
    // End of variables declaration//GEN-END:variables
}
