package SupavisioJ.FrameConfigSave;

import SupavisioJ.MainFrame.MainFrame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractButton;
import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.WindowConstants;
import javax.swing.JFrame;

/**
 *FrameConfigSave is the frame launch if the user wants to change the saving options
 */
public class FrameConfigSave extends JFrame {
    
    private MainFrame supavisioJFrame;
    
    /**
     * Creates a new frame FrameConfigSave
     */
    public FrameConfigSave(MainFrame supavisioJFrame) {
        initComponents();
        this.supavisioJFrame = supavisioJFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveImg = new JCheckBox();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        saveImg.setText(tr("sauvegarder images"));
        saveImg.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                saveImgActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(saveImg)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(saveImg)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is called if the corresponding checbox is selected and indicates to the MainFrame the corresponding setting.
     */
    private void saveImgActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveImgActionPerformed
        AbstractButton AB = (AbstractButton) evt.getSource();
        supavisioJFrame.setSaveImg(AB.getModel().isSelected());
    }//GEN-LAST:event_saveImgActionPerformed
    
    public String tr(String strToTranslate){
        return supavisioJFrame.tr(strToTranslate);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JCheckBox saveImg;
    // End of variables declaration//GEN-END:variables
}
