/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SupavisioJ.MainFrame;

import SupavisioJ.ConvertListFiles.ADC.ADC;
import SupavisioJ.ConvertListFiles.FrameC.FrameC;
import SupavisioJ.DataFilePIXE.DataFilePIXE;
import SupavisioJ.Spectra.Spectra;
import ij.IJ;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author vivien
 */
public class MainFrame extends javax.swing.JFrame {
    FrameC frameConfigLst = new FrameC();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass()
                    .getResource("/SupavisioJ/ressources/images" + "/atome-16.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOpenLst = new javax.swing.JButton();
        jLabelAsk = new javax.swing.JLabel();
        jButtonOpenPixe = new javax.swing.JButton();
        jButtonParamLst = new javax.swing.JButton();
        jButtonParamPIXE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SupavisioJ");

        jButtonOpenLst.setText("Ouvrir un fichier .lst");
        jButtonOpenLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenLstActionPerformed(evt);
            }
        });

        jLabelAsk.setText("Que voulez-vous faire?");

        jButtonOpenPixe.setText("Ouvrir un fichier .pixe");
        jButtonOpenPixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenPixeActionPerformed(evt);
            }
        });

        jButtonParamLst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SupavisioJ/ressources/images/avance-parametres-32.png"))); // NOI18N
        jButtonParamLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParamLstActionPerformed(evt);
            }
        });

        jButtonParamPIXE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SupavisioJ/ressources/images/avance-parametres-32.png"))); // NOI18N
        jButtonParamPIXE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParamPIXEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabelAsk))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonOpenLst, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonParamLst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonOpenPixe, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonParamPIXE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAsk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOpenLst)
                    .addComponent(jButtonParamLst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOpenPixe)
                    .addComponent(jButtonParamPIXE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpenLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenLstActionPerformed
        frameConfigLst.openLST();
    }//GEN-LAST:event_jButtonOpenLstActionPerformed

    private void jButtonParamLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParamLstActionPerformed
        frameConfigLst.setVisible(true);
    }//GEN-LAST:event_jButtonParamLstActionPerformed

    private void jButtonOpenPixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenPixeActionPerformed
        DataFilePIXE filePx=selectFilesPIXE();
	ADC adcPIXE = filePx.open(); 
        Spectra spectraPIXE= new Spectra(adcPIXE);
        spectraPIXE.plotSpectra("SupavisioJ","Spectre PIXE").showVisible();
    }//GEN-LAST:event_jButtonOpenPixeActionPerformed

    private void jButtonParamPIXEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParamPIXEActionPerformed
        IJ.log("Fonctionnalité non codée pour le moment");
    }//GEN-LAST:event_jButtonParamPIXEActionPerformed

    private DataFilePIXE selectFilesPIXE(){
        DataFilePIXE filePx=null;
        try{
          JFileChooser jF = new JFileChooser();//création dun nouveau filechosser
          jF.setApproveButtonText("OK"); //intitulé du bouton
          jF.setMultiSelectionEnabled(false);

          jF.showOpenDialog(null); //affiche la boite de dialogue

          File selectedFile = jF.getSelectedFile(); 
          filePx=new DataFilePIXE(selectedFile.getAbsolutePath());
        }
        catch (Exception e){
          IJ.log("Erreur");
        }
        return filePx;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOpenLst;
    private javax.swing.JButton jButtonOpenPixe;
    private javax.swing.JButton jButtonParamLst;
    private javax.swing.JButton jButtonParamPIXE;
    private javax.swing.JLabel jLabelAsk;
    // End of variables declaration//GEN-END:variables
}
